### ISSUE TITLE
ITF-4-01 - Create registration

### ISSUE THREAD

**Issue by YriyQKoty** [GUPY-Team/ITF#15]
<i>Create registration/login. User should be authorized via email + password or external services (Google, etc.)<i>
[View backlog](https://docs.google.com/spreadsheets/d/1eZl81zXK061wwNwQUvnImYCj3IxJwj_IVyoj4RxS2G0/edit#gid=0&range=C18:C20)

**Comment by neistow** [comment]
Merged into master via #19
